### ISSUE TITLE
Project Component

### ISSUE THREAD

**Issue by stanleylew5** [acm-ucr/developer-station#32]
![image](https://github.com/user-attachments/assets/6f5c78e3-1fb3-432f-9602-743b0f7c900b)

The entire thing should be clickable, you can ignore the bubbles on the outside. props passed in should be the name of the project, where it'll link to, description, and difficulty

**Comment by iambyt3z** [comment]
Reference Convo:

Q. For the Project Component, only the button needs to be clickable right?
Ans: Yeah the entire bubble train type thing. The project name doesn't have to be.

Q. Would we send the train image as a prop or is it static?
Ans: Static
